-- =========================
-- 社員情報テーブル
-- =========================
CREATE TABLE IF NOT EXISTS employee (
    employee_id VARCHAR(50) PRIMARY KEY,
    employee_name VARCHAR(50),
    password VARCHAR(100),
    birthday DATE,
    mail VARCHAR(50),
    role VARCHAR(50),
    work_start TIME,
    work_end TIME,
    enabled TINYINT DEFAULT 1,
    locked TINYINT DEFAULT 0,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
-- =========================
-- 勤怠時間テーブル
-- =========================
CREATE TABLE IF NOT EXISTS attendance (
    attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id VARCHAR(50),
    clock_in TIMESTAMP,
    clock_out TIMESTAMP,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
);

-- =========================
-- 休暇情報テーブル
-- =========================
CREATE TABLE IF NOT EXISTS vacation ( 
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    employee_id VARCHAR(50) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    vacation_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) DEFAULT 'APPLYING',
    reason VARCHAR(255),
    approver_id VARCHAR(50),
    approve_date DATE,
    rejected_reason VARCHAR(255),
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employee(employee_id),
    FOREIGN KEY (approver_id) REFERENCES employee(employee_id)
);

CREATE INDEX idx_vacation_employee_date
ON vacation (employee_id, start_date);

-- =========================
-- 管理者テーブル
-- =========================
CREATE TABLE IF NOT EXISTS employee_superior (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id VARCHAR(50) NOT NULL,
    superior_id VARCHAR(50) NOT NULL,
    create_date DATETIME,
    update_date DATETIME,
    CONSTRAINT fk_employee FOREIGN KEY (employee_id) REFERENCES employee(employee_id),
    CONSTRAINT fk_superior FOREIGN KEY (superior_id) REFERENCES employee(employee_id)
);

-- =========================
-- 祝日、社休テーブル
-- =========================
CREATE TABLE IF NOT EXISTS holiday_calendar (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
    holiday_date DATE NOT NULL,
    holiday_type VARCHAR(20) NOT NULL,
    description VARCHAR(50),
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);